### ISSUE TITLE
Performance characteristics.

### ISSUE THREAD

**Issue by dpc** [jorisgio/spinrust#2]
I'm wondering what are the performance implications when using this instead of `std::mutex`. Is the shorter latency during congestion the only benefit? How is the time of acquiring the lock in non-contested case?

Specifically, I'm considering this crate for a case when contention should never, ever happen, and spinlock will only protect "malicious" usage by the user. I wonder if I can get a better performance in intended workload (no contention ever).

**Comment by jorisgio** [comment]
`std::mutex`  is a wrapper around the system mutex. On linux, it uses the pthread mutex implementation, which in turns with glibc uses linux futex. The performance of the uncontended path in this case is basically a single atomic compare and swap instruction.

This crate also need a single compare and swap atomic instruction for read lock and a single fetch add atomic instruction for write lock. In this regard, performance is theoretically the same. The difference is in the contested path. Maybe the only potential difference is that with this crate the uncontested path can be inlined while with std::mutex you have to call down to C, but to be honest i'm not sure it would make a real difference.

**Comment by dpc** [comment]
Thanks!
